# Generated by Django 5.0.3 on 2024-03-04 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_taken', models.DateField(default=datetime.datetime.today)),
                ('debt_name', models.CharField(max_length=100)),
                ('debt_mobile', models.PositiveIntegerField()),
                ('debt_address', models.CharField(max_length=1000)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_start_date', models.DateField(default=datetime.datetime.today)),
                ('debt_end_date', models.DateField(default=datetime.datetime.today)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
